import type { ProjectState } from "@/types/project";
import { getTechLabel } from "@/data/tech-stacks";
import { APP_TYPES } from "@/lib/constants";

export function generateProjectMd(state: ProjectState): string {
  const { identity, architecture } = state;
  const ts = identity.techStack;

  const techStackLines: string[] = [];
  if (ts.framework)
    techStackLines.push(
      `- **Framework:** ${getTechLabel("framework", ts.framework)}`
    );
  if (ts.styling)
    techStackLines.push(
      `- **Styling:** ${getTechLabel("styling", ts.styling)}`
    );
  if (ts.database)
    techStackLines.push(
      `- **Database:** ${getTechLabel("database", ts.database)}`
    );
  if (ts.auth)
    techStackLines.push(
      `- **Authentication:** ${getTechLabel("auth", ts.auth)}`
    );
  if (ts.deployment)
    techStackLines.push(
      `- **Deployment:** ${getTechLabel("deployment", ts.deployment)}`
    );
  if (ts.componentLibrary)
    techStackLines.push(
      `- **Component Library:** ${getTechLabel("componentLibrary", ts.componentLibrary)}`
    );

  const appTypeLabel =
    APP_TYPES.find((t) => t.id === architecture.appType)?.label ??
    architecture.appType;

  const enabledLayers = architecture.layers.filter((l) => l.enabled);
  const layerLines = enabledLayers.map((layer) => {
    let line = `- **${layer.name}**`;
    if (layer.technologies.length > 0) {
      line += ` (${layer.technologies.join(", ")})`;
    }
    if (layer.notes) {
      line += `\n  ${layer.notes}`;
    }
    return line;
  });

  const featureList = state.features.map(
    (f) => `- [${f.name}](features/${f.slug}.md)`
  );

  const sections: string[] = [
    `# ${identity.name || "Untitled Project"}`,
    "",
    identity.purpose ? `> ${identity.purpose}` : "",
    "",
    "---",
    "",
    "## Tech Stack",
    "",
    ...(techStackLines.length > 0
      ? techStackLines
      : ["_No tech stack selected._"]),
    "",
    "## Architecture",
    "",
    `**Application Type:** ${appTypeLabel || "Not specified"}`,
    "",
    "### Layers",
    "",
    ...(layerLines.length > 0 ? layerLines : ["_No architecture layers defined._"]),
    "",
    "## Documentation",
    "",
    "- [Architecture Details](docs/ARCHITECTURE.md)",
    "- [Conventions](docs/CONVENTIONS.md)",
    "- [Styling Guide](docs/STYLING.md)",
    ...(state.database.approach !== "skip"
      ? ["- [Database Schema](docs/SCHEMA.md)"]
      : []),
    "",
    "## Features",
    "",
    ...(featureList.length > 0
      ? ["See [Features Index](features/FEATURES-INDEX.md) for full details.", "", ...featureList]
      : ["_No features defined yet._"]),
    "",
    "## Tasks",
    "",
    state.tasks.length > 0
      ? `See [Tasks Master](tasks/TASKS-MASTER.md) for the full task list (${state.tasks.length} tasks).`
      : "_No tasks defined yet._",
    "",
    "---",
    "",
    "*Generated by [Framewright](https://framewright.dev)*",
    "",
  ];

  return sections.filter((s) => s !== undefined).join("\n");
}
