import type { ProjectState, Task } from "@/types/project";

function formatTaskNumber(n: number): string {
  return `task-${String(n).padStart(3, "0")}`;
}

function taskSlug(task: Task): string {
  const slug = task.name
    ? task.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")
    : "";
  return `${formatTaskNumber(task.taskNumber)}${slug ? `-${slug}` : ""}`;
}

export function generateContextStartersMd(state: ProjectState): string {
  const { tasks, features } = state;

  const taskPrompts = tasks.map((task) => {
    const linkedFeatures = features.filter((f) =>
      task.featureIds.includes(f.id)
    );
    const featureFiles = linkedFeatures
      .map((f) => `features/${f.slug || "unnamed"}.md`)
      .join(", then read ");

    const readFeatures = featureFiles ? `, then read ${featureFiles}` : "";

    return [
      `### ${formatTaskNumber(task.taskNumber)}: ${task.name || "Unnamed"}`,
      "",
      "```",
      `Read PROJECT.md, then read docs/CONVENTIONS.md${readFeatures}, then read tasks/${taskSlug(task)}.md.`,
      `Complete the task described in the task file. On completion, review your work against the Definition of Done.`,
      "```",
      "",
    ].join("\n");
  });

  const sections: string[] = [
    "# Context Window Starters",
    "",
    "> Copy-paste these prompts into your AI tool at the start of each coding session.",
    "> Each prompt loads the exact context needed for one task.",
    "",
    "---",
    "",
    ...(taskPrompts.length > 0
      ? taskPrompts
      : [
          "_No tasks defined. Create tasks in the wizard to generate starter prompts._",
          "",
        ]),
    "---",
    "",
    "*Generated by [Framewright](https://framewright.dev)*",
    "",
  ];

  return sections.join("\n");
}

/** Generate a single context starter prompt for one task (for clipboard copy) */
export function generateSingleContextStarter(
  task: Task,
  state: ProjectState
): string {
  const linkedFeatures = state.features.filter((f) =>
    task.featureIds.includes(f.id)
  );
  const featureFiles = linkedFeatures
    .map((f) => `features/${f.slug || "unnamed"}.md`)
    .join(", then read ");

  const readFeatures = featureFiles ? `, then read ${featureFiles}` : "";

  return `Read PROJECT.md, then read docs/CONVENTIONS.md${readFeatures}, then read tasks/${taskSlug(task)}.md. Complete the task described in the task file. On completion, review your work against the Definition of Done.`;
}
