import type { ProjectState } from "@/types/project";
import { getTechLabel } from "@/data/tech-stacks";

export function generatePrimeMd(state: ProjectState): string {
  const { identity, features, tasks } = state;
  const ts = identity.techStack;

  const stackParts: string[] = [];
  if (ts.framework) stackParts.push(getTechLabel("framework", ts.framework));
  if (ts.database) stackParts.push(getTechLabel("database", ts.database));
  if (ts.auth) stackParts.push(getTechLabel("auth", ts.auth));
  if (ts.deployment) stackParts.push(getTechLabel("deployment", ts.deployment));

  const featureLines =
    features.length > 0
      ? features.map(
          (f) =>
            `- ${f.name || "Unnamed"} → \`features/${f.slug || "unnamed"}.md\``
        )
      : ["_No features defined._"];

  const statusIcon: Record<string, string> = {
    done: "✓",
    "in-progress": "→",
    blocked: "✗",
    "not-started": "○",
  };

  const taskLines =
    tasks.length > 0
      ? tasks.map((t) => {
          const icon = statusIcon[t.status ?? "not-started"] ?? "○";
          const num = `task-${String(t.taskNumber).padStart(3, "0")}`;
          return `- ${icon} ${num}: ${t.name || "Unnamed"}`;
        })
      : ["_No tasks defined._"];

  const sections: string[] = [
    `# ${identity.name || "Untitled Project"} — AI Navigator`,
    "",
    identity.purpose ? `> ${identity.purpose}` : "",
    "",
    stackParts.length > 0 ? `**Stack:** ${stackParts.join(" + ")}` : "",
    "",
    "---",
    "",
    "## How to Use This Framework",
    "",
    "You are an AI assistant working on this project. Follow this protocol:",
    "",
    "1. Read this file to orient yourself",
    "2. Open `CONTEXT-WINDOW-STARTERS.md` — copy the prompt for your assigned task",
    "3. Follow the reading sequence in that starter exactly — do not skip files",
    "4. Stay within the **File Boundaries** listed in your task file",
    "5. Read the **Out of Scope** section before touching any file",
    "6. On completion, verify your work against the **Definition of Done**",
    "7. Do not refactor, clean up, or improve code outside your task's scope",
    "8. Before closing: update your task file — set **Status** and add a note under **## Session Notes** (what you completed, decisions made, what remains)",
    "",
    "---",
    "",
    "## Quick Reference",
    "",
    "| What you need | Where to find it |",
    "|---|---|",
    "| Full project overview | `PROJECT.md` |",
    "| Critical coding rules (read every session) | `docs/CONVENTIONS-QUICKREF.md` |",
    "| Full conventions detail | `docs/CONVENTIONS.md` |",
    "| Architecture detail | `docs/ARCHITECTURE.md` |",
    "| Database schema | `docs/SCHEMA.md` |",
    "| Features list | `features/FEATURES-INDEX.md` |",
    "| All tasks | `tasks/TASKS-MASTER.md` |",
    "| Copy-paste task prompts | `CONTEXT-WINDOW-STARTERS.md` |",
    "",
    "---",
    "",
    "## Features",
    "",
    ...featureLines,
    "",
    "## Task Status",
    "",
    "> ○ Not started · → In progress · ✓ Done · ✗ Blocked",
    "",
    ...taskLines,
    "",
    "---",
    "",
    "*Generated by [Framewright](https://framewright.dev)*",
    "",
  ].filter((s) => s !== undefined);

  return sections.join("\n");
}
