import type { ProjectState } from "@/types/project";
import { getTechLabel } from "@/data/tech-stacks";
import { getAllConventionQuestions } from "@/data/conventions";

/** Extract the top conventions as brief bullet-point rules */
function getTopConventionRules(state: ProjectState, limit = 6): string[] {
  const allQuestions = getAllConventionQuestions();

  return state.conventions.decisions
    .slice(0, limit)
    .map((decision) => {
      const question = allQuestions.find((q) => q.id === decision.questionId);
      if (!question) return null;
      const selectedOption = question.options.find(
        (o) => o.id === decision.selectedOptionId
      );
      if (!selectedOption) return null;
      // Take the first meaningful line from the generated text
      const firstLine =
        selectedOption.generatedText
          .split("\n")
          .map((l) => l.trim())
          .find((l) => l.length > 0) ?? selectedOption.label;
      const cleaned = firstLine
        .replace(/^#+\s*/, "")
        .replace(/\*\*/g, "")
        .trim();
      return `- ${cleaned}`;
    })
    .filter(Boolean) as string[];
}

/** CLAUDE.md — auto-loaded by Claude Code at the start of every session */
export function generateClaudeMd(state: ProjectState): string {
  const { identity } = state;
  const ts = identity.techStack;

  const stackLines: string[] = [];
  if (ts.framework)
    stackLines.push(`- Framework: ${getTechLabel("framework", ts.framework)}`);
  if (ts.database)
    stackLines.push(`- Database: ${getTechLabel("database", ts.database)}`);
  if (ts.auth)
    stackLines.push(`- Auth: ${getTechLabel("auth", ts.auth)}`);
  if (ts.deployment)
    stackLines.push(`- Deployment: ${getTechLabel("deployment", ts.deployment)}`);
  if (ts.styling)
    stackLines.push(`- Styling: ${getTechLabel("styling", ts.styling)}`);

  const topRules = getTopConventionRules(state);

  return [
    `# ${identity.name || "Untitled Project"}`,
    "",
    identity.purpose ? `> ${identity.purpose}` : "",
    "",
    "## Stack",
    "",
    ...(stackLines.length > 0 ? stackLines : ["_No tech stack defined._"]),
    "",
    "## Critical Rules",
    "",
    ...(topRules.length > 0
      ? topRules
      : ["_See `docs/CONVENTIONS-QUICKREF.md` for coding conventions._"]),
    "",
    "## Navigation",
    "",
    "- **Start here:** read `PRIME.md` for project context and AI protocol",
    "- **Find your task:** `CONTEXT-WINDOW-STARTERS.md`",
    "- **Quick conventions:** `docs/CONVENTIONS-QUICKREF.md`",
    "- **Full context:** `PROJECT.md`",
    "",
    "---",
    "",
    "*Generated by [Framewright](https://framewright.dev)*",
    "",
  ].join("\n");
}

/** .cursorrules — auto-loaded by Cursor IDE */
export function generateCursorRules(state: ProjectState): string {
  const { identity } = state;
  const ts = identity.techStack;

  const stackParts: string[] = [];
  if (ts.framework) stackParts.push(getTechLabel("framework", ts.framework));
  if (ts.database) stackParts.push(getTechLabel("database", ts.database));
  if (ts.auth) stackParts.push(getTechLabel("auth", ts.auth));

  const topRules = getTopConventionRules(state);

  return [
    `# ${identity.name || "Untitled Project"}`,
    "",
    identity.purpose || "",
    "",
    "## Stack",
    "",
    stackParts.length > 0 ? stackParts.join(", ") : "_Not defined_",
    "",
    "## Rules",
    "",
    ...(topRules.length > 0
      ? topRules
      : ["See docs/CONVENTIONS-QUICKREF.md"]),
    "",
    "## Project Framework",
    "",
    "Read PRIME.md for project context and AI operating protocol.",
    "See CONTEXT-WINDOW-STARTERS.md for current tasks.",
    "See docs/CONVENTIONS-QUICKREF.md for coding conventions.",
    "",
    "*Generated by Framewright*",
  ].join("\n");
}

/** .github/copilot-instructions.md — auto-loaded by GitHub Copilot */
export function generateCopilotInstructions(state: ProjectState): string {
  const { identity } = state;
  const ts = identity.techStack;

  const stackLines: string[] = [];
  if (ts.framework)
    stackLines.push(`- ${getTechLabel("framework", ts.framework)}`);
  if (ts.database)
    stackLines.push(`- ${getTechLabel("database", ts.database)}`);
  if (ts.auth)
    stackLines.push(`- ${getTechLabel("auth", ts.auth)}`);

  const topRules = getTopConventionRules(state);

  return [
    `# GitHub Copilot Instructions — ${identity.name || "Untitled Project"}`,
    "",
    identity.purpose || "",
    "",
    "## Tech Stack",
    "",
    ...stackLines,
    "",
    "## Coding Conventions",
    "",
    ...(topRules.length > 0
      ? topRules
      : ["See docs/CONVENTIONS-QUICKREF.md"]),
    "",
    "## Project Context",
    "",
    "Read PRIME.md for full project context and navigation guide.",
    "",
    "*Generated by Framewright*",
  ].join("\n");
}
